# Cloudflare Pages configuration
"$schema" = "./node_modules/wrangler/config-schema.json"
name = "eisen-svelte-pwa"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_als"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KV"
id = "70281fa565714be7b7c26af569556071"

[[d1_databases]]
binding = "DB"
database_name = "eisen-db"
database_id = "7cf88082-4cb8-4ba8-ad03-c26db5f710c4"
preview_database_id = "local-eisen-db"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "eisen-attachments"

[vars]
APP_NAME = "Eisen"
RECORD_SCHEMA_VERSION = "1"
